name: Free RDP with LocalXpose

on:
  workflow_dispatch:

jobs:
  build:
    name: Enable RDP and Start LocalXpose Tunnel
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable Remote Desktop
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "MySecurePassword123!" -Force)

      - name: Install Chocolatey
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install LocalXpose via Chocolatey
        shell: powershell
        run: |
          choco install localxpose -y

      - name: Start LocalXpose Tunnel and Capture Endpoint
        shell: powershell
        run: |
          $logPath = "$env:USERPROFILE\loclx_output.txt"
          $exePath = "C:\ProgramData\chocolatey\lib\localxpose\tools\loclx.exe"

          # Start tunnel in background and redirect output
          Start-Process -FilePath $exePath -ArgumentList "tunnel tcp --port 3389 --raw-mode" -RedirectStandardOutput $logPath -NoNewWindow

          # Wait for tunnel to initialize
          Start-Sleep -Seconds 15

          # Try to extract endpoint from log
          if (Test-Path $logPath) {
            $endpoint = Get-Content $logPath | Select-String -Pattern "tcp://" | Select-Object -First 1
            if ($endpoint) {
              Write-Output "LocalXpose TCP Tunnel is active!"
              Write-Output "Public RDP Endpoint: $($endpoint.Line)"
              Write-Output "RDP Username: runneradmin"
              Write-Output "RDP Password: MySecurePassword123!"
            } else {
              Write-Output "Tunnel started, but no endpoint found in logs."
            }
          } else {
            Write-Output "Log file not found. Tunnel may not have started correctly."
          }
