name: Windows - LiteManager

on:
  workflow_dispatch:

jobs: 
  build:
    name: Start Building
    runs-on: windows-latest
    steps:
      - name: Downloading & Installing Essentials
        run: |
          curl -L -o Downloads.bat "https://gitlab.com/chamod12/m_win-10_github_rdp/-/raw/main/Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
