name: Free RDP with Pinggy

on:
  workflow_dispatch:

jobs:
  build:
    name: Enable RDP and Start Tunnel
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "MySecurePassword123!" -Force)

      - name: Download Pinggy Client
        run: |
          Invoke-WebRequest -Uri "https://pinggy.io/download/windows/pinggy.exe" -OutFile "pinggy.exe"
          Start-Sleep -Seconds 3
          if (!(Test-Path "pinggy.exe")) { throw "Pinggy download failed." }

      - name: Launch Pinggy Tunnel
        run: |
          $pinggyPath = "$PWD\pinggy.exe"
          if (!(Test-Path $pinggyPath)) { throw "Pinggy executable not found." }
          Start-Process -FilePath $pinggyPath -ArgumentList 'tcp --forward 127.0.0.1:3389' -WindowStyle Hidden
