name: Free RDP with Loophole

on:
  workflow_dispatch:

jobs:
  build:
    name: Enable RDP and Start Loophole Tunnel
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "MySecurePassword123!" -Force)

      - name: Download Loophole CLI
        run: |
          curl -L -o loophole.zip "https://loophole.cloud/download/windows/loophole-cli-latest.zip"
          Start-Sleep -Seconds 2

      - name: Extract Loophole (using Shell.Application)
        run: |
          $zipPath = "loophole.zip"
          $destination = "$PWD\\loophole"
          New-Item -ItemType Directory -Force -Path $destination
          $shell = New-Object -ComObject Shell.Application
          $zip = $shell.NameSpace((Convert-Path $zipPath))
          $target = $shell.NameSpace($destination)
          $target.CopyHere($zip.Items(), 0x10)
          Start-Sleep -Seconds 2

      - name: Start Loophole Tunnel
        run: |
          $exePath = "$PWD\\loophole\\loophole.exe"
          if (!(Test-Path $exePath)) { throw "Loophole executable not found at $exePath" }
          & $exePath tcp 3389
