name: Free RDP with Localhost.run

on:
  workflow_dispatch:

jobs:
  build:
    name: Enable RDP and Start Localhost Tunnel
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable Remote Desktop
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "MySecurePassword123!" -Force)

      - name: Install SSH Client
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Start SSH Tunnel and Extract Public URL
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no -R 80:localhost:3389 ssh.localhost.run | tee tunnel.log &
          sleep 10
          PUBLIC_URL=$(grep -o 'https://[^ ]*' tunnel.log | head -n 1)
          echo "Public URL: $PUBLIC_URL"
          echo "RDP Username: runneradmin"
          echo "RDP Password: MySecurePassword123!"
