name: Free RDP with Localhost.run

on:
  workflow_dispatch:

jobs:
  build:
    name: Enable RDP and Start Localhost Tunnel
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable Remote Desktop
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "MySecurePassword123!" -Force)

      - name: Download plink (SSH client for Windows)
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://the.earth.li/~sgtatham/putty/latest/w64/plink.exe" -OutFile "$env:USERPROFILE\plink.exe"

      - name: Start SSH Tunnel with localhost.run
        shell: powershell
        run: |
          $plinkPath = "$env:USERPROFILE\plink.exe"
          if (!(Test-Path $plinkPath)) { throw "plink.exe not found." }
          
          Write-Output "Starting tunnel to localhost.run..."
          Start-Process -FilePath $plinkPath -ArgumentList "-R 80:localhost:3389 ssh.localhost.run" -NoNewWindow
          Start-Sleep -Seconds 10
          
          Write-Output "Tunnel should now be active."
          Write-Output "RDP Username: runneradmin"
          Write-Output "RDP Password: MySecurePassword123!"
