name: Free RDP Setup

on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy Windows RDP
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download Setup Script
        run: |
          curl -L -o setup.bat "https://raw.githubusercontent.com/Riders004/rdp/main/setup.bat"
          cmd /c setup.bat

      - name: Start RDP Services
        run: |
          cmd /c show.bat
          cmd /c loop.bat
