name: Free RDP with Loophole

on:
  workflow_dispatch:

jobs:
  build:
    name: Enable RDP and Start Loophole Tunnel
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "MySecurePassword123!" -Force)

      - name: Download Loophole CLI
        run: |
          curl -L -o loophole.zip "https://loophole.cloud/download/windows/loophole-cli-latest.zip"
          Start-Sleep -Seconds 2
          if ((Get-Item loophole.zip).Length -lt 10000) { throw "Download failed or returned an invalid file." }

      - name: Extract Loophole
        run: |
          Expand-Archive loophole.zip -DestinationPath loophole
          if (!(Test-Path "loophole\loophole.exe")) { throw "Loophole executable not found after extraction." }

      - name: Start Loophole Tunnel
        run: |
          .\loophole\loophole.exe tcp 3389
