name: Free RDP with Pinggy

on:
  workflow_dispatch:

jobs:
  build:
    name: Enable RDP and Start Tunnel
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "MySecurePassword123!" -Force)

      - name: Download Pinggy Client
        run: |
          curl -L -o pinggy.exe "https://pinggy.io/download/windows/pinggy.exe"
          Start-Sleep -Seconds 2
          if (!(Test-Path "pinggy.exe")) { throw "Pinggy download failed." }

      - name: Start Pinggy Tunnel
        run: |
          Start-Process -FilePath ".\pinggy.exe" -ArgumentList 'tcp --forward 127.0.0.1:3389' -NoNewWindow
