name: Free RDP with Pagekite

on:
  workflow_dispatch:

jobs:
  build:
    name: Enable RDP and Start Pagekite Tunnel
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable Remote Desktop
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "MySecurePassword123!" -Force)

      - name: Download Pagekite
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://pagekite.net/pk/pagekite.py" -OutFile "$env:USERPROFILE\pagekite.py"

      - name: Start Pagekite Tunnel
        shell: powershell
        run: |
          $kiteName = "rdptest.pagekite.me"
          $kiteSecret = "letmein"
          $pagekitePath = "$env:USERPROFILE\pagekite.py"
          $cmd = "python $pagekitePath localhost:3389 tcp://$kiteName"
          Write-Output "Starting Pagekite tunnel..."
          Start-Process -FilePath "python" -ArgumentList "$pagekitePath localhost:3389 tcp://$kiteName" -NoNewWindow
          Start-Sleep -Seconds 10
          Write-Output "Tunnel should now be active."
          Write-Output "RDP Username: runneradmin"
          Write-Output "RDP Password: MySecurePassword123!"
          Write-Output "Connect using: $kiteName (via Pagekite TCP tunnel)"
