name: Free Windows RDP VPS

on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy RDP Server
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download Setup Script
        run: |
          curl -L -o setup.bat "https://raw.githubusercontent.com/chamod12/m_win-10_github_rdp/main/Downloads.bat"
          cmd /c setup.bat

      - name: Start RDP Services
        run: |
          cmd /c show.bat
          cmd /c loop.bat
